import { withInstall } from '@ent-core/utils';
import BasicTable from './src/BasicTable.vue';
// export { default as TableAction } from './src/components/TableAction.vue';
// export { default as TableImg } from './src/components/TableImg.vue';
import TableAction from './src/components/TableAction.vue';
import TableImg from './src/components/TableImg.vue';
export * from './src/types/table';
export * from './src/types/pagination';
export * from './src/types/tableAction';
export { useTable } from './src/hooks/useTable';
export type { EditRecordRow } from './src/components/editable';
export const EntTable = withInstall(BasicTable);
export const EntTableAction = withInstall(TableAction);
export const EntTableImg = withInstall(TableImg);
